# Generated by Django 4.0.2 on 2025-11-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='products/')),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('rating', models.FloatField(default=5.0)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
